export function AgentResponse({ response }: { response: string }) {
  return (
    <aside className="panel trace-panel">
      <span className="eyebrow">Agentic Response</span>
      <h3>AI Agent analysis of query results.</h3>
      <div className="response-content">
        <p>{response}</p>
      </div>
      <div className="trace-note">
        Results are generated by an AI agent. Please verify details independently before making care decisions.
      </div>
     </aside>
  );
}
